### PR TITLE
gitlab, bitbucket, gogs and gitea

### PR DESCRIPTION
**Pull request by MichielDx**
#4

### CODE REVIEW

**Comment by MichielDx** [comment]
Feel free to refactor this 😉 
Not the best code

**Comment by xxhomey19** [comment]
Hi @MichielDx 
I have viewed your PR, and I think there is too many similar code. 
In my opinion, I suggest you get `window.location.href` or `window.location.domain` to determine which CSS selector should be used. Then, run domain-specific function.
Just reduce duplicate code as more as possible, move them to a separate new function. 👍

**Comment by MichielDx** [comment]
Hey, I would do that but I'm quite busy at the moment. You mind taking a look at it?

**Comment by xxhomey19** [comment]
Sure. I will do it.

**Comment by evaryont** [comment]
How hard would it be to support not only gitlab.com, but also other self-hosted installations of Gitlab, Gogs, and Gitea? This is very similar to #2.

**Comment by xxhomey19** [comment]
Hi @evaryont 
It seems that there is no conclusion yet. This PR could only support some specific domains.

**Pull request merged**
